; freemlib for Neo-Geo - System Functions
;==============================================================================;
; Hardware Dipswitches (MVS-only)

; Read data from REG_DIPSW
;==============================================================================;
; Software Dipswitches

; Read data from BIOS_GAME_DIP
;==============================================================================;
; Debug Dipswitches (address found in header; $10E)
;==============================================================================;
; Calendar (MVS-only)
; the various DATE_TIME elements.

; mvsCal_GetDayNum
; Get day number (1-366).
;------------------------------------------------------------------------------;

;==============================================================================;
; Backup RAM (MVS-only, $D00000-$D0FFFF)
