; instruments.inc - Instrument Definitions file
;==============================================================================;
; [Instructions]
; Copy and edit me!

; Instrument structure is still under construction, however.
;==============================================================================;
; * FM instruments
instruments_FM:
	; 29 bytes per instrument

; * SSG instruments
instruments_SSG:
	; 3 bytes per instrument

; * ADPCM-B instruments
instruments_PCMB:
	; 5 bytes per instrument
